name: Jellyfin Server

on:
  workflow_dispatch:

jobs:
    run-jellyfin:
    runs-on: ubuntu-latest
  
  steps:
    - name: Checkout
      uses: actions/checkout@v4
  
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y rclone jellyfin curl unzip
  
    - name: Setup rclone config
      run: |
        mkdir -p $HOME/.config/rclone
        echo "${{ secrets.RCLONE_CONFIG }}" > $HOME/.config/rclone/rclone.conf
  
    - name: Mount MEGA
      run: |
        mkdir -p $HOME/media
        rclone mount "Mega:3TA" $HOME/media --vfs-cache-mode writes --daemon
        
        echo "Waiting for mount..."
        for i in {1..30}; do
          if ls $HOME/media > /dev/null 2>&1; then
            echo "Mount ready"
            break
          fi
          sleep 2
        done
  
        echo "Files inside mount:"
        ls -lah $HOME/media
  
    - name: Stop system Jellyfin
      run: |
        sudo systemctl stop jellyfin || true
        sudo systemctl disable jellyfin || true
  
    - name: Start Jellyfin
      run: |
        jellyfin --datadir $HOME/jellyfin-data --cachedir $HOME/jellyfin-cache &
  
    - name: Install Ngrok
      run: |
        curl -L https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -o ngrok.tgz
        tar -xvzf ngrok.tgz
        chmod +x ngrok
        ./ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}
  
    - name: Start Ngrok
      run: |
        ./ngrok http 8096 &
  
    - name: Show Ngrok URL
      run: |
        sleep 10
        curl http://127.0.0.1:4040/api/tunnels
  
    - name: Keep server alive
      run: sleep 21600
