name: Jellyfin MEGA Server

on:
  workflow_dispatch:  # allows manual run

jobs:
  run-jellyfin:
    runs-on: ubuntu-latest

    steps:
      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Setup rclone config
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF }}" > ~/.config/rclone/rclone.conf

      - name: Install Docker
        run: |
          sudo apt update
          sudo apt install -y docker.io

      - name: Mount MEGA
        run: |
          mkdir /mnt/media
          rclone mount "Mega:3TA" /mnt/media --vfs-cache-mode writes --daemon

      - name: Start Jellyfin
        run: |
          sudo docker run -d \
            --name jellyfin \
            -p 8096:8096 \
            -v /mnt/media:/media \
            jellyfin/jellyfin:latest

      - name: Install Ngrok
        run: |
          curl -s https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -o ngrok.zip
          unzip ngrok.zip
          chmod +x ngrok
          ./ngrok authtoken ${{ secrets.NGROK_TOKEN }}
          ./ngrok http 8096 &
