name: Jellyfin MEGA Server

on:
  workflow_dispatch:  # allows manual run

jobs:
  run-jellyfin:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Install rclone
      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      # 2️⃣ Setup rclone config
      - name: Setup rclone config
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF }}" > ~/.config/rclone/rclone.conf

      # 3️⃣ Mount MEGA
      - name: Mount MEGA
        run: |
          mkdir -p $HOME/media
          rclone mount "Mega:3TA" $HOME/media --vfs-cache-mode writes --daemon
      
      - name: Check MEGA mount
        run: |
          ls -lah /home/runner/media

      # 4️⃣ Install Jellyfin
      - name: Install Jellyfin
        run: |
          sudo apt update
          sudo apt install -y apt-transport-https software-properties-common wget
          wget -O - https://repo.jellyfin.org/ubuntu/jellyfin_team.gpg.key | sudo apt-key add -
          echo "deb [arch=$( dpkg --print-architecture )] https://repo.jellyfin.org/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/jellyfin.list
          sudo apt update
          sudo apt install -y jellyfin

      # 5️⃣ Start Jellyfin
      - name: Start Jellyfin
        run: sudo jellyfin &

      - name: Install and Start Ngrok
        run: |
          curl -L https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -o ngrok.tgz
          tar -xvzf ngrok.tgz
          chmod +x ngrok
      
          ./ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}
      
          ./ngrok http 8096 > /dev/null &
      
          sleep 5
      
          curl http://127.0.0.1:4040/api/tunnels
          
      - name: Keep server alive
        run: sleep 21600
